apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- cluster-issuer.yaml

#PATCH NOT WORKING:
# patches:
# - path: patch-helm-chart-version.yaml
#   target:
#     kind: Kustomization

