apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml

helmCharts:
  - name: sealed-secrets
    repo: https://bitnami-labs.github.io/sealed-secrets/
    version: 2.17.9
    namespace: sealed-secrets
    releaseName: sealed-secrets
    valuesFile: values.yaml
    includeCRDs: true