apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - patch-me-see-overlays
  template:
    metadata:
      name: '{{.name}}'
      annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
        argocd.argoproj.io/sync-options: Prune=false
        argocd.argoproj.io/sync-wave: '{{.syncWave}}'
      labels:
        gitops: operator
    spec:
      project: default
      syncPolicy: 
        syncOptions:
        - SkipDryRunOnMissingResource=true
      source:
        repoURL: https://github.com/andifg/gitopsify.git
        targetRevision: main
        path: '{{.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.namespace}}'
  templatePatch: |
    {{- if .ignoreDifferences }}
    spec:
      ignoreDifferences:
    {{ toYaml .ignoreDifferences | indent 6 }}
    {{- end}}