apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
spec:
  generators:
  - list:
      elements:
      - values:
          name: k8s-dasbhoard
          path: components/apps/kubernetes-dashboard/overlays/k8s-default
          namespace: k8s-dashboard
      - values:
          name: cert-manager
          path: components/apps/cert-manager/overlays/k8s-default
          namespace: cert-manager
      - values:
          name: velero
          path: components/apps/velero/overlays/k8s-default
          namespace: velero