apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml

helmCharts:
  - name: velero
    repo: https://vmware-tanzu.github.io/helm-charts/
    version: 11.1.1
    namespace: velero
    releaseName: velero
    valuesFile: values.yaml